name: GitHub Actions CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_JSON_CORE: 1

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew install-bundler-gems

      - run: brew style $GITHUB_REPOSITORY

      - run: brew untap homebrew/core

      - run: brew json hello
