name: GitHub Actions CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_JSON_CORE: 1

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Bundler RubyGems
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Bundler RubyGems
        run: brew install-bundler-gems

      - run: brew test-bot --only-tap-syntax

  tests:
    strategy:
      matrix:
        version: ["macos-latest", "ubuntu-latest"]
      fail-fast: false
    runs-on: ${{ matrix.version }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew untap homebrew/core

      - run: brew json hello
